### ISSUE TITLE
Mouse scroll for coffee categories

### ISSUE THREAD

**Issue by kurnakovv** [Ulyanov-programmer/Coffee-House#1]
@Ulyanov-programmer Can you add mouse scroll for coffee categories? We already have buttons for scroll, but i think it's not comfortable :(
Site is really cool!

**Comment by Ulyanov-programmer** [comment]
@KurnakovMaksim Hello!
If you knew with which crutches the category section was made...
I will try to make a scroll in the near future, although this will also be a crutch.

**Comment by Ulyanov-programmer** [comment]
The issue was resolved by [commit](https://github.com/Ulyanov-programmer/Coffee-House/commit/609bca42dfd2411522a4494042072421d891cfae), in which scrolling was added (including on mobile devices), as well as the binding to the slider was removed.

**Comment by kurnakovv** [comment]
Thanks, I think stay better. Take a star :)
